// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter/greeter.proto

package greeter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CounterRequest struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CounterRequest) Reset()         { *m = CounterRequest{} }
func (m *CounterRequest) String() string { return proto.CompactTextString(m) }
func (*CounterRequest) ProtoMessage()    {}
func (*CounterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_797d732b8e529c0d, []int{0}
}

func (m *CounterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterRequest.Unmarshal(m, b)
}
func (m *CounterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterRequest.Marshal(b, m, deterministic)
}
func (m *CounterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterRequest.Merge(m, src)
}
func (m *CounterRequest) XXX_Size() int {
	return xxx_messageInfo_CounterRequest.Size(m)
}
func (m *CounterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CounterRequest proto.InternalMessageInfo

func (m *CounterRequest) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type CounterResponse struct {
	ResNum               int64    `protobuf:"varint,1,opt,name=res_num,json=resNum,proto3" json:"res_num,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CounterResponse) Reset()         { *m = CounterResponse{} }
func (m *CounterResponse) String() string { return proto.CompactTextString(m) }
func (*CounterResponse) ProtoMessage()    {}
func (*CounterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_797d732b8e529c0d, []int{1}
}

func (m *CounterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterResponse.Unmarshal(m, b)
}
func (m *CounterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterResponse.Marshal(b, m, deterministic)
}
func (m *CounterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterResponse.Merge(m, src)
}
func (m *CounterResponse) XXX_Size() int {
	return xxx_messageInfo_CounterResponse.Size(m)
}
func (m *CounterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CounterResponse proto.InternalMessageInfo

func (m *CounterResponse) GetResNum() int64 {
	if m != nil {
		return m.ResNum
	}
	return 0
}

func (m *CounterResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func init() {
	proto.RegisterType((*CounterRequest)(nil), "CounterRequest")
	proto.RegisterType((*CounterResponse)(nil), "CounterResponse")
}

func init() { proto.RegisterFile("greeter/greeter.proto", fileDescriptor_797d732b8e529c0d) }

var fileDescriptor_797d732b8e529c0d = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0x4a, 0x5c, 0x7c,
	0xce, 0xf9, 0xa5, 0x79, 0x25, 0xa9, 0x45, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x02,
	0x5c, 0xcc, 0x79, 0xa5, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x20, 0xa6, 0x92, 0x15,
	0x17, 0x3f, 0x5c, 0x4d, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x38, 0x17, 0x7b, 0x51, 0x6a,
	0x71, 0x3c, 0x42, 0x21, 0x5b, 0x51, 0x6a, 0xb1, 0x5f, 0x69, 0xae, 0x10, 0x1f, 0x17, 0x53, 0x66,
	0x81, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x81, 0x91, 0x35, 0x17, 0xbb, 0x3b,
	0xc4, 0x42, 0x21, 0x03, 0x2e, 0x76, 0xa8, 0x31, 0x42, 0xfc, 0x7a, 0xa8, 0x96, 0x4a, 0x09, 0xe8,
	0xa1, 0xd9, 0xa0, 0xc4, 0xa0, 0xc1, 0xe8, 0xa4, 0x14, 0xa5, 0x90, 0x9e, 0x59, 0x92, 0x51, 0x9a,
	0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x97, 0x54, 0x52, 0x56, 0xaa, 0x9f, 0x9e, 0x99, 0x58, 0x90,
	0x99, 0x9c, 0x09, 0xf3, 0x46, 0x12, 0x1b, 0xd8, 0x1f, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x6b, 0xec, 0xa0, 0x97, 0xe0, 0x00, 0x00, 0x00,
}
